meta_product_name: "ParkBuddies"
meta_title: "ParkBuddies – L'appli qui transforme les parcs en terrains d'amitié. Connectez, Rencontrez, Partagez"
meta_description: "Les parents peuvent se retrouver pour aller au parc ensemble et profiter de moments entre adultes"
meta_image: "cover.png" # should exist in `app/assets/images/`
